/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.jp1.visao;

import com.jp1.Renderer.TableRenderer;
import com.jp1.controle.AcessoriosControle;
import com.jp1.controle.ClienteControle;
import com.jp1.controle.IAcessoriosControle;
import com.jp1.controle.IClienteControle;
import com.jp1.controle.ILocacaoControle;
import com.jp1.controle.LocacaoControle;
import com.jp1.modelos.Acessorios;
import com.jp1.modelos.Categoria;
import com.jp1.modelos.Locacao;
import com.jp1.modelos.TipoDoCliente;
import com.jp1.tools.Data;
import com.jp1.tools.Numero;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
/**
 *
 * @author aluno
 */
public class TelaLocacoesAtivas extends javax.swing.JInternalFrame {

    /**
     * Creates new form TelaDevolucao
     */
    int linha = 0;
    
    ILocacaoControle locacaoControle = new LocacaoControle();
    IClienteControle clienteControle = new ClienteControle();
    IAcessoriosControle acessoriosControle = new AcessoriosControle();
    
    public TelaLocacoesAtivas() {
        initComponents();
        
        AdicionarTela(jInternalFrame1);
        listarComboBox();
        try {
            listar(locacaoControle.listar());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void listarComboBox(){
        jComboBoxTipoDoCliente.setModel(new DefaultComboBoxModel<>(TipoDoCliente.values()));
    }
    
    public void AdicionarTela(javax.swing.JInternalFrame tela){
        tela.setSize(941, 417);
        ((BasicInternalFrameUI)tela.getUI()).setNorthPane(null);
        jDesktopPane1.removeAll();
        jDesktopPane1.add(tela);
        tela.setVisible(true);
    }
    
    public void listar(ArrayList<Locacao> array){
        Iterator<Locacao> locacoes = array.iterator();
        DefaultTableModel model = (DefaultTableModel) jTableModelos.getModel();
        model.setNumRows(0);
        
        while(locacoes.hasNext()){
            Locacao locacao = locacoes.next();
            String dados[] = locacao.toString().split(";");
//            try {
//                dados[3] = categoriaControle.buscar(Integer.parseInt(dados[3])).getDescricao();
//            } catch (Exception e) {
//                e.printStackTrace();
//                JOptionPane.showMessageDialog(null, e.getMessage());
//            }
//            dados[4] = Numero.real(dados[4]);
//            dados[5] = Numero.real(dados[5]);
//            dados[8] = Numero.numeral(dados[8]) + " Km";
//            dados[12] = "";
            model.addRow(dados);
        }
        jTableModelos.setModel(model);
    }
    
    public void setarMascara(javax.swing.JFormattedTextField campo, String mask, char placeHolderCharcter){
        try{
            MaskFormatter mascara = new MaskFormatter();
            mascara.setMask(mask);
            mascara.setPlaceholderCharacter(placeHolderCharcter);
            campo.setFormatterFactory(new DefaultFormatterFactory(mascara));
        }catch(Exception e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModelos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jComboBoxTipoDoCliente = new javax.swing.JComboBox<>();
        jLabelCPF_CNPJ = new javax.swing.JLabel();
        jFormattedTextFieldCPF_CNPJ = new javax.swing.JFormattedTextField();
        setarMascara(jFormattedTextFieldCPF_CNPJ, "###.###.###-##", ' ');
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        jInternalFrame1.setBorder(null);
        jInternalFrame1.setVisible(true);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setPreferredSize(new java.awt.Dimension(941, 417));

        jScrollPane1.setPreferredSize(new java.awt.Dimension(952, 244));
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane1MouseClicked(evt);
            }
        });

        jTableModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDENTIFICADOR", "DATA INÍCIO", "DATA FIM", "VALOR DA LOCAÇÃO", "MOTORISTA", "CLIENTE", "VEÍCULO", "ACESSÓRIOS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableModelos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableModelos.setFocusable(false);
        jTableModelos.setName("TabelaModelos"); // NOI18N
        jTableModelos.setRowHeight(50);
        jTableModelos.setSelectionBackground(new java.awt.Color(52, 135, 231));
        jTableModelos.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableModelos.setShowHorizontalLines(true);
        jTableModelos.getTableHeader().setResizingAllowed(false);
        jTableModelos.getTableHeader().setReorderingAllowed(false);
        jTableModelos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableModelosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableModelos);
        if (jTableModelos.getColumnModel().getColumnCount() > 0) {
            jTableModelos.getColumnModel().getColumn(0).setMinWidth(150);
            jTableModelos.getColumnModel().getColumn(0).setPreferredWidth(150);
            jTableModelos.getColumnModel().getColumn(0).setCellRenderer(new TableRenderer());
            jTableModelos.getColumnModel().getColumn(1).setMinWidth(150);
            jTableModelos.getColumnModel().getColumn(1).setPreferredWidth(150);
            jTableModelos.getColumnModel().getColumn(1).setCellRenderer(new TableRenderer());
            jTableModelos.getColumnModel().getColumn(2).setMinWidth(150);
            jTableModelos.getColumnModel().getColumn(2).setPreferredWidth(150);
            jTableModelos.getColumnModel().getColumn(2).setCellRenderer(new TableRenderer());
            jTableModelos.getColumnModel().getColumn(3).setMinWidth(150);
            jTableModelos.getColumnModel().getColumn(3).setPreferredWidth(150);
            jTableModelos.getColumnModel().getColumn(3).setCellRenderer(new TableRenderer());
            jTableModelos.getColumnModel().getColumn(4).setMinWidth(150);
            jTableModelos.getColumnModel().getColumn(4).setPreferredWidth(150);
            jTableModelos.getColumnModel().getColumn(4).setCellRenderer(new TableRenderer());
            jTableModelos.getColumnModel().getColumn(5).setMinWidth(150);
            jTableModelos.getColumnModel().getColumn(5).setPreferredWidth(150);
            jTableModelos.getColumnModel().getColumn(5).setCellRenderer(new TableRenderer());
            jTableModelos.getColumnModel().getColumn(6).setMinWidth(150);
            jTableModelos.getColumnModel().getColumn(6).setPreferredWidth(150);
            jTableModelos.getColumnModel().getColumn(6).setCellRenderer(new TableRenderer());
            jTableModelos.getColumnModel().getColumn(7).setMinWidth(150);
            jTableModelos.getColumnModel().getColumn(7).setPreferredWidth(150);
            jTableModelos.getColumnModel().getColumn(7).setCellRenderer(new TableRenderer());
        }

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Tipo do Cliente");

        jComboBoxTipoDoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoDoClienteActionPerformed(evt);
            }
        });

        jLabelCPF_CNPJ.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelCPF_CNPJ.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCPF_CNPJ.setText("CPF");

        jFormattedTextFieldCPF_CNPJ.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);
        jFormattedTextFieldCPF_CNPJ.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFormattedTextFieldCPF_CNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jFormattedTextFieldCPF_CNPJKeyTyped(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("BUSCAR LOCAÇÃO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setText("DEVOLVER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextFieldModelo.setEnabled(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Modelo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxTipoDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldModelo)
                        .addGap(220, 220, 220)))
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabelCPF_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFormattedTextFieldCPF_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 907, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboBoxTipoDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelCPF_CNPJ)
                    .addComponent(jFormattedTextFieldCPF_CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jInternalFrame1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setBorder(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("DEVOLUÇÃO");

        jDesktopPane1.setPreferredSize(new java.awt.Dimension(941, 417));

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 941, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 417, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        Run.telaPrincipal.jPanelVeiculosExp.setVisible(false);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jTableModelosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableModelosMouseClicked
        // TODO add your handling code here:
        if(jTableModelos.getSelectedRow() != -1){
            try {
                //jTextFieldModelo.setText(locacaoControle.buscar(Integer.parseInt(jTableModelos.getValueAt(linha, 0).toString())).getVeiculo().getModelo().getDescricao());
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }

    }//GEN-LAST:event_jTableModelosMouseClicked

    private void jScrollPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane1MouseClicked
        // TODO add your handling code here:
        //limpar();
    }//GEN-LAST:event_jScrollPane1MouseClicked

    private void jComboBoxTipoDoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoDoClienteActionPerformed
        // TODO add your handling code here:
        switch (TipoDoCliente.valueOf(jComboBoxTipoDoCliente.getSelectedItem().toString())) {
            case PESSOAFISICA:
            jLabelCPF_CNPJ.setText("CPF");
            setarMascara(jFormattedTextFieldCPF_CNPJ, "###.###.###-##", ' ');
            break;
            case PESSOAJURIDICA:
            jLabelCPF_CNPJ.setText("CNPJ");
            setarMascara(jFormattedTextFieldCPF_CNPJ, "##.###.###/####-##", ' ');
            break;
        }
    }//GEN-LAST:event_jComboBoxTipoDoClienteActionPerformed

    private void jFormattedTextFieldCPF_CNPJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextFieldCPF_CNPJKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldCPF_CNPJKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            listar(locacaoControle.listarRelacionados(jFormattedTextFieldCPF_CNPJ.getText()));
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            Acessorios acessorio = locacaoControle.buscar(Integer.parseInt(jTableModelos.getValueAt(linha, 0).toString())).getAcessorios();
            acessorio.setQuantidadeLocada(acessorio.getQuantidadeLocada() - 1);
            acessoriosControle.alterar(acessorio);
            JOptionPane.showMessageDialog(null, "Valor do Caução devolvido.");
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<TipoDoCliente> jComboBoxTipoDoCliente;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF_CNPJ;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCPF_CNPJ;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModelos;
    private javax.swing.JTextField jTextFieldModelo;
    // End of variables declaration//GEN-END:variables
}
